apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
  namespace: gpu-operator
data:
{{- if .Values.platform.openshift }}
  unsupported: ""
{{ else }}
  unsupported: openshift
{{- end }}

  driver: "{{ .Values.nvidia.driver.repository }}/{{ .Values.nvidia.driver.image }}:{{ .Values.nvidia.driver.version }}"
  toolkit: "{{ .Values.nvidia.toolkit.repository }}/{{ .Values.nvidia.toolkit.image }}:{{ .Values.nvidia.toolkit.version }}"
  devicePlugin: "{{ .Values.nvidia.devicePlugin.repository }}/{{ .Values.nvidia.devicePlugin.image }}:{{ .Values.nvidia.devicePlugin.version }}"
