apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: "gpu-operator"
    {{ $.Release.labels }}
data:
{{- if .Values.platform.openshift }}
  KUBE_UNSUPPORTED_FLAVOR: ""
{{ else }}
  KUBE_UNSUPPORTED_FLAVOR: openshift
{{- end }}

  NVIDIA_DRIVER: "{{ .Values.driver.repository }}/{{ .Values.driver.image }}:{{ .Values.driver.version }}"
  NVIDIA_TOOLKIT: "{{ .Values.toolkit.repository }}/{{ .Values.toolkit.image }}:{{ .Values.toolkit.version }}"
  NVIDIA_DEVICE_PLUGIN: "{{ .Values.devicePlugin.repository }}/{{ .Values.devicePlugin.image }}:{{ .Values.devicePlugin.version }}"
  {{- if and (ne (float64 (toString (.Values.operator.clusterversion))) 4.1) (ne (float64 (toString (.Values.operator.clusterversion))) 4.2) }}
  NVIDIA_DCGM_EXPORTER: "{{ .Values.dcgmExporter.repository }}/{{ .Values.dcgmExporter.image }}:{{ .Values.dcgmExporter.version }}"
  NVIDIA_DCGM_POD_EXPORTER: "{{ .Values.dcgmPodExporter.repository }}/{{ .Values.dcgmPodExporter.image }}:{{ .Values.dcgmPodExporter.version }}"
  {{- end }}
