apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  operator:
    defaultRuntime: crio
    deployGFD: true
    validator:
      repository: nvcr.io/nvidia/k8s
      image: cuda-sample
      version: "vectoradd-cuda10.2-ubi8"
      imagePullSecrets: []
  driver:
    repository: nvcr.io/nvidia
    image: driver
    version: "450.80.02"
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  toolkit:
    repository: nvcr.io/nvidia/k8s
    version: 1.4.3-ubi8
    image: container-toolkit
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  devicePlugin:
    repository: nvcr.io/nvidia
    image: k8s-device-plugin
    version: v0.7.3-ubi8
    args:
      - "--mig-strategy=none"
      - "--pass-device-specs=false"
      - "--fail-on-init-error=true"
      - "--device-list-strategy=envvar"
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  dcgmExporter:
    repository: nvcr.io/nvidia/k8s
    image: dcgm-exporter
    version: 2.0.13-2.1.2-ubi8
    args:
      - "-f"
      - "/etc/dcgm-exporter/default-counters.csv"
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  gfd:
    repository: nvcr.io/nvidia
    image: gpu-feature-discovery
    version: v0.3.0
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    migStrategy: none
    discoveryIntervalSeconds: 60
