apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-operator
  labels:
    app.kubernetes.io/component: "gpu-operator"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gpu-operator
      app.kubernetes.io/component: "gpu-operator"
  template:
    metadata:
      labels:
        name: gpu-operator
        app.kubernetes.io/component: "gpu-operator"
    spec:
      serviceAccountName: gpu-operator
      containers:
      - name: gpu-operator
        image: nvidia/gpu-operator:latest
        imagePullPolicy: Always
        command: ["gpu-operator"]
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAME
          value: "gpu-operator"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          exec:
            command: ["stat", "/tmp/operator-sdk-ready"]
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        ports:
        - containerPort: 60000
          name: metrics
