apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-driver
  namespace: gpu-operator-resources
  labels:
    app.kubernetes.io/component: "driver"
data:
  oci-nvidia-hook-json: | 
    {
        "version": "1.0.0",
        "hook": {
            "path": "/run/nvidia/driver/usr/bin/nvidia-container-runtime-hook",
            "args": ["nvidia-container-runtime-hook", "prestart"],
            "env": [
                "PATH=/run/nvidia/driver/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ]
        },
        "when": {
            "always": true,
            "commands": [".*"]
        },
        "stages": ["prestart"]
    }
