{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}
  labels:
    {{- include "node-feature-discovery.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-feature-discovery.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-feature-discovery.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
