name: Renovate

on:
  schedule:
     - cron: "0 9 * * *" # every day at 9:00 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.0
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: '["NVIDIA/gpu-operator"]'
          RENOVATE_ONBOARDING: false
